---

common_base_packages:
  - curl
  - wget
  - git
  - unzip
  - vim
  - htop
  - tree
  - jq
  - ca-certificates
  - gnupg
  - lsb-release
  - net-tools
  - software-properties-common

docker_edition: ce                   
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users:
  - "{{ ansible_user_id | default('root') }}"

docker_old_packages_debian:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc

docker_old_packages_redhat:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

tools_extra_packages:
  - unzip
  - zip
  - ncdu
  - tmux
  - net-tools
  - lsof

tools_install_kubectl: false
tools_install_terraform: false
tools_install_awscli: false
tools_install_helm: false

tools_kubectl_version: "v1.31.0"
tools_terraform_version: "1.9.5"
tools_helm_version: "v3.15.4"


cleanup_paths:
  - /tmp/ansible_demo
  - /tmp/old_build_artifacts


cleanup_find_root: /var/cache/apt/archives
cleanup_find_patterns:
  - "*.deb"
cleanup_find_age_days: 0    # only match files older than N days (0 = any age)

cleanup_packages: []

cleanup_docker_prune: false     # docker system prune -af --volumes
cleanup_apt_autoremove: true    # apt-get autoremove -y && apt-get autoclean -y

### --- network_check role 
network_check_targets:
  - 8.8.8.8
  - 1.1.1.1
  - github.com
