FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json tsconfig.json ./

COPY scripts ./scripts
COPY .db ./.db

RUN npm install

# Set environment variables
ENV NODE_ENV=development

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
